version: 2

models:
  - name: cpa_and_roas
    description: 'This table contains the cost per acquisition and return on ad spend, by source, and per month'
    meta:
      owner: 'Noa'
      subscribers: ['@marketing_team']