version: 2

models:
  - name: orders
    tests:
      - unique:
          column_name: id  # Assuming 'id' is the primary key column
      - elementary.column_anomalies:
          column_name: amount
          anomaly_sensitivity: 3
          time_bucket:
            period: day
            count: 1
          detection_period:
            period: day
            count: 7
          training_period:
            period: day
            count: 28

  - name: real_time_orders
    tests:
      - elementary.custom_test_sql:
          name: amount_less_than_max_price
          config:
            severity: error
          sql: |
            SELECT
              ro.id as order_id,
              ro.amount,
              rp.max_price
            FROM {{ model }} ro
            JOIN raw_products rp ON ro.product_id = rp.id
            WHERE ro.amount > rp.max_price

  - name: stg_orders
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies
