version: 2

models:
  - name: customers
    description: This table has basic information about a customer, as well as some
      derived facts based on a customer's orders
    meta:
      owner: "Maayan"
    config:
      elementary:
        timestamp_column: "signup_date"
      tags:
        - customer-data
        - pii
    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - relationships:
              config:
                severity: warn
                owner: ["@data-ops"]
              to: ref('stg_signups')
              field: customer_id
          - not_null:
              name: not_null_customer_id
              description: Ensures that every record has a valid customer_id

      - name: first_name
        description: Customer's first name. PII.

      - name: last_name
        description: Customer's last name. PII.

      - name: first_order
        description: Date (UTC) of a customer's first order

      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order

      - name: number_of_orders
        description: Count of the number of orders a customer has placed

      - name: customer_lifetime_value
        description: Total value (AUD) of a customer's orders
        tests:
          - accepted_values:
              name: positive_customer_lifetime_value
              description: Ensures that customer_lifetime_value is always positive
              values: ['> 0']

      - name: customer_email
        description: Customer's email. PII.
        tests:
          - unique:
              config:
                owner: ["@data-ops"]
          - elementary.column_anomalies:
              config:
                owner: ["@data-ops"]
              column_anomalies:
                - missing_count
          - dbt_utils.expression_is_true:
              name: valid_customer_email
              description: Ensures that customer_email follows a valid email format
              expression: "regexp_like(customer_email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$')"

      - name: signup_date
        description: Date (UTC) of a customer's signup to the online shop.

    tests:
      - dbt_utils.expression_is_true:
          name: first_order_before_most_recent
          description: Ensures that first_order is always earlier than or equal to most_recent_order
          expression: "first_order <= most_recent_order OR (first_order IS NULL AND most_recent_order IS NULL)"
      
      - dbt_utils.expression_is_true:
          name: consistent_customer_names
          description: Ensures that customer first and last names are not null and contain only alphabetic characters
          expression: "regexp_like(first_name, '^[A-Za-z]+$') AND regexp_like(last_name, '^[A-Za-z]+$')"
      
      - dbt_utils.expression_is_true:
          name: number_of_orders_consistency
          description: Ensures that number_of_orders is consistent with the presence of first_order and most_recent_order
          expression: "(number_of_orders > 0 AND first_order IS NOT NULL AND most_recent_order IS NOT NULL) OR (number_of_orders = 0 AND first_order IS NULL AND most_recent_order IS NULL)"
      
      - dbt_utils.expression_is_true:
          name: signup_before_first_order
          description: Ensures that the signup_date is always earlier than or equal to the first_order date
          expression: "signup_date <= first_order OR (signup_date IS NOT NULL AND first_order IS NULL)"

  - name: orders
    description: This table has basic information about orders, as well as some derived
      facts based on payments
    meta:
      owner: "Or"
    config:
      tags: ["finance", "sales"]
      elementary:
        timestamp_column: "order_date"

    tests:
      - elementary.dimension_anomalies:
          dimensions:
            - customer_id
          config:
            owner: ["@data-ops"]
            tags: ["stability"]
    columns:
      - name: order_id
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - relationships:
              config:
                severity: warn
                owner: ["@data-ops"]
              to: ref('customers')
              field: customer_id

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'
        tests:
          - accepted_values:
              config:
                tags: ["customer_success"]
                severity: warn
                owner: ["@data-ops"]
              values: ["placed", "shipped", "completed", "return_pending", "returned"]
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["placed", "shipped", "completed", "return_pending", "returned"]
              quote_values: true
              config:
                severity: warn
                owner: ["@data-ops"]

      - name: amount
        description: Total amount (AUD) of the order
        tests:
          - elementary.column_anomalies:
              config:
                severity: warn
                owner: ["@data-ops"]
              column_anomalies:
                - zero_count
                - zero_percent

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card

  - name: returned_orders
    description: This table contains all of the returned orders
    meta:
      owner: "Or"
    config:
      tags: ["finance"]
      elementary:
        timestamp_column: "order_date"

    tests:
      - elementary.schema_changes:
          config:
            owner: ["@finance-team"]
    columns:
      - name: order_id
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - relationships:
              config:
                severity: warn
                owner: ["@customer-team"]
              to: ref('customers')
              field: customer_id

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'
        tests:
          - accepted_values:
              config:
                severity: warn
                owner: ["@customer-team"]
              values: ["return_pending", "returned"]

      - name: amount
        description: Total amount (AUD) of the order
        tests:
          - elementary.column_anomalies:
              config:
                owner: ["@finance-team"]
              column_anomalies:
                - zero_count
                - zero_percent

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card

  - name: lost_orders
    description: This table contains all of the lost orders
    meta:
      owner: "Or"
    config:
      tags: ["finance"]
      elementary:
        timestamp_column: "order_date"

    tests:
      - elementary.schema_changes_from_baseline
    columns:
      - name: order_id
        description: This is a unique identifier for an order
        data_type: integer

      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - relationships:
              config:
                severity: warn
                owner: ["@customer-team"]
              to: ref('customers')
              field: customer_id

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'
        tests:
          - accepted_values:
              config:
                severity: warn
                owner: ["@finance-team"]
              values: ["shipped", "return_pending"]

      - name: amount
        description: Total amount (AUD) of the order
        tests:
          - elementary.column_anomalies:
              config:
                severity: warn
                owner: ["@finance-team"]
              column_anomalies:
                - zero_count
                - zero_percent

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card
