version: 2

models:
  - name: orders
    tests:
      - unique:
          column_name: id  # Assuming 'id' is the primary key
    columns:
      - name: amount
        tests:
          - elementary.column_anomalies:
              anomaly_direction: both
              anomaly_sensitivity: 3
              column_anomalies:
                - average
              timestamp_column: order_date  # Assuming there's an order_date column

  - name: real_time_orders
    tests:
      - dbt_utils.expression_is_true:
          expression: "amount <= (SELECT MAX(price) FROM {{ source('raw', 'products') }})"  # Adjust source name if needed

  - name: cpa_and_roas
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies