version: 2

models:
  - name: orders
    columns:
      - name: order_id  # Assuming 'order_id' is the primary key
        tests:
          - unique
    tests:
      - elementary.column_anomalies:
          column_name: amount
          anomaly_detection:
            sensitivity: 2  # Adjust sensitivity as needed

  - name: real_time_orders
    columns:
      - name: amount
        tests:
          - accepted_values:
              min_value: 0  # Adjust min and max values as appropriate for your business
              max_value: 10000