version: 2

models:
  - name: cpa_and_roas
    meta:
      subscribers: "@marketing_team"
    columns:
      - name: source
      - name: month
      - name: ad_spend
      - name: revenue
      - name: cpa
      - name: roas