version: 2

models:
  - name: cpa_and_roas
    owner: DE-engineering-team

  - name: sessions
    owner: DE-engineering-team

  - name: ads_spend
    owner: DE-engineering-team

  - name: attribution_touches
    owner: DE-engineering-team

  - name: agg_sessions
    owner: DE-engineering-team

  - name: marketing_ads
    owner: DE-engineering-team

  - name: customer_conversions
    owner: DE-engineering-team

  - name: orders
    owner: DE-engineering-team

  - name: real_time_orders
    owner: DE-engineering-team

  - name: historical_orders
    owner: DE-engineering-team
