
version: 2

models:
  - name: orders
    tests:
      - unique:
          column_name: order_id  # Assuming 'order_id' is the primary key
      - elementary.column_anomalies:
          column_name: amount
          anomaly_sensitivity: 2  # Adjust sensitivity as needed
          time_bucket:
            period: day
            count: 1
  
  - name: real_time_orders
    tests:
      - elementary.sql:
          name: amount_not_exceeding_max_price
          query: |
            SELECT
              order_id,
              amount
            FROM {{ model }}
            LEFT JOIN {{ source('raw', 'products') }} as raw_products
              ON {{ model }}.product_id = raw_products.product_id
            WHERE amount > raw_products.max_price
  