models:
  - name: orders
    tests:
      - unique:
          column_name: order_id  # Assuming order_id is the primary key
    columns:
      - name: amount
        tests:
          - elementary.column_anomalies:
              column_anomalies:
                - average
                - sum
              timestamp_column: order_date  # Assuming there's an order_date column

  - name: real_time_orders
    columns:
      - name: amount
        tests:
          - accepted_range:
              min_value: 0  # Assuming amount should always be non-negative
              max_value: 10000  # Adjust this value based on your business logic
