version: 2

models:
  - name: orders
    columns:
      - name: order_id
        tests:
          - unique
    tests:
      - elementary.column_anomalies:
          column_anomalies:
            - average
          column_name: amount
          timestamp_column: order_date

  - name: real_time_orders
    tests:
      - dbt_utils.expression_is_true:
          expression: "amount <= (select max(price) from {{ source('products', 'raw_products') }})"

  - name: stg_orders
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies

  - name: stg_payments
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies
