models:
  - name: orders
    columns:
      - name: id
        tests:
          - unique
      - name: amount
        tests:
          - elementary.column_anomalies:
              column_anomalies:
                - zero_count
                - zero_percent
    tests:
      - elementary.dimension_anomalies:
          dimensions:
            - customer_id
      - relationships:
          field: customer_id
          to: ref('customers')
      - accepted_values:
          values:
            - placed
            - shipped
            - completed
            - return_pending
            - returned
          column_name: status
      - dbt_expectations.expect_column_values_to_be_in_set:
          column_name: status
          value_set:
            - placed
            - shipped
            - completed
            - return_pending
            - returned