version: 2

models:
  - name: orders
    columns:
      - name: order_id  # Assuming this is the primary key
        tests:
          - unique
    tests:
      - elementary.column_anomalies:
          column_name: amount
          anomaly_sensitivity: 3

  - name: real_time_orders
    columns:
      - name: amount
        tests:
          - accepted_values:
              min_value: 0  # Assuming the minimum value is 0
              max_value: 10000  # Assuming a reasonable maximum value