version: 2

sources:
  - name: elementary
    schema: jaffle_shop_elementary
    tables:
      - name: elementary_exposures
        columns:
          - name: unique_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - finance
                  meta:
                    owner:
                      - Ella
