version: 2

models:
  - name: stg_customers
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
    columns:
      - name: customer_id
        tests:
          - unique:
              config:
                severity: warn
          - relationships:
              to: ref('stg_signups')
              field: customer_id

    description: Stores the core customer information from the raw customers source
      table, providing a clean and standardized view of customer details. This staging
      model transforms the raw customer data by selecting key identifying fields like
      customer ID, first name, and last name. The model serves as a foundational layer
      for downstream analytics and customer-related transformations in the data pipeline.
  - name: stg_orders
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance", "sales"]
      elementary:
        timestamp_column: "order_date"
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
      - name: status
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["placed", "shipped", "completed", "return_pending", "returned"]
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["placed", "shipped", "completed", "return_pending", "returned"]
              quote_values: true

    description: Staging table for orders from the raw orders source, capturing essential
      order details including order ID, customer ID, order date, and status. This
      model provides a clean, standardized view of order information for downstream
      analytics and reporting in the finance and sales domains. The model renames
      columns for clarity and selects key attributes from the source table to create
      a consistent and accessible representation of order data.
  - name: stg_payments
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
        tests:
          - unique:
              config:
                severity: warn
      - name: payment_method
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["credit_card", "coupon", "bank_transfer", "gift_card"]

    description: Staging table for payment information that transforms raw payment
      data into a clean, usable format. The model converts payment amounts from cents
      to dollars and renames key columns for easier analysis. This table provides
      a standardized view of payment transactions, enabling finance teams and analysts
      to easily track and understand payment details across the organization.
  - name: stg_signups
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
      elementary:
        timestamp_column: "signup_date"
    columns:
      - name: signup_id
        tests:
          - unique:
              config:
                severity: warn
      - name: customer_email
        tests:
          - unique
          - elementary.column_anomalies:
              sensitivity: 2
              config:
                severity: warn
              column_anomalies:
                - missing_count
    description: This model contains the core signup information for customers, transformed
      from the raw signups validation source. It provides a clean, standardized view
      of user signup data, including unique identifiers, email addresses, and signup
      dates. The model renames and selects key fields to create a consistent and accessible
      staging layer for downstream analytics and reporting.
