version: 2

models:
  - name: stg_customers
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
    columns:
      - name: customer_id
        tests:
          - unique:
              config:
                severity: warn
          - relationships:
              to: ref('stg_signups')
              field: customer_id

          - unique:
              description: The column should contain only unique values
              config:
                tags:
                  - stability
                severity: error
              meta:
                owner:
                  - Or
      - name: first_name
        data_tests:
          - unique:
              description: The column should contain only unique values
              config:
                tags:
                  - stability
                severity: error
              meta:
                owner:
                  - Or
      - name: last_name
        data_tests:
          - unique:
              description: The column should contain only unique values
              config:
                tags:
                  - stability
                severity: error
              meta:
                owner:
                  - Or
  - name: stg_orders
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance", "sales"]
      elementary:
        timestamp_column: "order_date"
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
          - unique:
              description: The column should contain only unique values
              config:
                tags:
                  - stability
                severity: error
              meta:
                owner:
                  - Or
      - name: status
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["placed", "shipped", "completed", "return_pending", "returned"]
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["placed", "shipped", "completed", "return_pending", "returned"]
              quote_values: true

          - unique:
              description: The column should contain only unique values
              config:
                tags:
                  - stability
                severity: error
              meta:
                owner:
                  - Or
      - name: customer_id
        data_tests:
          - unique:
              description: The column should contain only unique values
              config:
                tags:
                  - stability
                severity: error
              meta:
                owner:
                  - Or
      - name: order_date
        data_tests:
          - unique:
              description: The column should contain only unique values
              config:
                tags:
                  - stability
                severity: error
              meta:
                owner:
                  - Or
  - name: stg_payments
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
        tests:
          - unique:
              config:
                severity: warn
          - unique:
              description: The column should contain only unique values
              config:
                tags:
                  - stability
                severity: error
              meta:
                owner:
                  - Or
      - name: payment_method
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["credit_card", "coupon", "bank_transfer", "gift_card"]
          - unique:
              description: The column should contain only unique values
              config:
                tags:
                  - stability
                severity: error
              meta:
                owner:
                  - Or

      - name: order_id
        data_tests:
          - unique:
              description: The column should contain only unique values
              config:
                tags:
                  - stability
                severity: error
              meta:
                owner:
                  - Or
      - name: amount
        data_tests:
          - unique:
              description: The column should contain only unique values
              config:
                tags:
                  - stability
                severity: error
              meta:
                owner:
                  - Or
  - name: stg_signups
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
      elementary:
        timestamp_column: "signup_date"
    columns:
      - name: signup_id
        tests:
          - unique:
              config:
                severity: warn
          - unique:
              description: The column should contain only unique values
              config:
                tags:
                  - stability
                severity: error
              meta:
                owner:
                  - Or
      - name: customer_email
        tests:
          - unique
          - elementary.column_anomalies:
              sensitivity: 2
              config:
                severity: warn
              column_anomalies:
                - missing_count
          - unique:
              description: The column should contain only unique values
              config:
                tags:
                  - stability
                severity: error
              meta:
                owner:
                  - Or
      - name: customer_id
        data_tests:
          - unique:
              description: The column should contain only unique values
              config:
                tags:
                  - stability
                severity: error
              meta:
                owner:
                  - Or
      - name: hashed_password
        data_tests:
          - unique:
              description: The column should contain only unique values
              config:
                tags:
                  - stability
                severity: error
              meta:
                owner:
                  - Or
      - name: signup_date
        data_tests:
          - unique:
              description: The column should contain only unique values
              config:
                tags:
                  - stability
                severity: error
              meta:
                owner:
                  - Or
