version: 2

models:
  - name: stg_customers
    description: This staging model ingests raw customer data from the `raw_customers_validation`
      table in the `jaffle_shop` schema of the `ELEMENTARY_TESTS` database. It renames
      the `id` column to `customer_id` and includes the `first_name` and `last_name`
      columns. This model serves as a centralized and cleaned representation of customer
      data, which is critical for downstream data analysis and reporting. The transformations
      performed in this model ensure data quality and consistency for data consumers.
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
    columns:
      - name: customer_id
        tests:
          - unique:
              config:
                severity: warn
          - relationships:
              to: ref('stg_signups')
              field: customer_id

  - name: stg_orders
    description: This model, `stg_orders`, represents the staging table for the orders
      data in the finance and sales domain. It serves as the foundation for downstream
      data models by extracting and transforming the raw orders data from the `ELEMENTARY_TESTS.jaffle_shop.raw_orders_validation`
      source. The key transformations performed include renaming the columns to more
      intuitive names, such as `order_id`, `customer_id`, `order_date`, and `status`,
      providing a clean and structured representation of the orders data for further
      analysis.
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance", "sales"]
      elementary:
        timestamp_column: "order_date"
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
      - name: status
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["placed", "shipped", "completed", "return_pending", "returned"]
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["placed", "shipped", "completed", "return_pending", "returned"]
              quote_values: true

  - name: stg_payments
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
        tests:
          - unique:
              config:
                severity: warn
      - name: payment_method
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["credit_card", "coupon", "bank_transfer", "gift_card"]

  - name: stg_signups
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
      elementary:
        timestamp_column: "signup_date"
    columns:
      - name: signup_id
        tests:
          - unique:
              config:
                severity: warn
      - name: customer_email
        tests:
          - unique
          - elementary.column_anomalies:
              sensitivity: 2
              config:
                severity: warn
              column_anomalies:
                - missing_count
