version: 2

models:
  - name: stg_customers
    description: This model represents the staging table for customer data. It serves
      as a centralized and curated source of customer information, including customer
      ID, first name, and last name. The model performs a simple renaming and restructuring
      of the raw customer data, preparing it for use in downstream analytical models.
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
    columns:
      - name: customer_id
        tests:
          - unique:
              config:
                severity: warn
          - relationships:
              to: ref('stg_signups')
              field: customer_id

  - name: stg_orders
    description: This model, `stg_orders`, is a staging table that stores the raw
      order data from the `raw_orders_validation` view in the `jaffle_shop` schema.
      It renames and selects the relevant columns, including `order_id`, `customer_id`,
      `order_date`, and `status`. This model serves the finance and sales teams by
      providing a clean and consistent data source for downstream analysis on orders
      and customer behavior.
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance", "sales"]
      elementary:
        timestamp_column: "order_date"
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
      - name: status
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["placed", "shipped", "completed", "return_pending", "returned"]
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["placed", "shipped", "completed", "return_pending", "returned"]
              quote_values: true

  - name: stg_payments
    description: This staging table, `stg_payments`, contains the raw payments data
      from the `jaffle_shop` data source. It is used to transform the raw data into
      a format that is more suitable for analysis by data consumers. The `amount`
      column is converted from cents to dollars, and the table includes the payment
      ID, order ID, and payment method. This model serves the finance domain and is
      owned by Idan.
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
        tests:
          - unique:
              config:
                severity: warn
      - name: payment_method
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["credit_card", "coupon", "bank_transfer", "gift_card"]

  - name: stg_signups
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
      elementary:
        timestamp_column: "signup_date"
    columns:
      - name: signup_id
        tests:
          - unique:
              config:
                severity: warn
      - name: customer_email
        tests:
          - unique
          - elementary.column_anomalies:
              sensitivity: 2
              config:
                severity: warn
              column_anomalies:
                - missing_count
