version: 2

models:
  - name: stg_customers
    description: This model, `stg_customers`, represents the staging table for customer
      data. It serves the purpose of storing the raw customer information, including
      the customer ID, first name, and last name, before further downstream processing
      and transformation. The model performs a simple renaming operation, mapping
      the source column names to the appropriate target column names, ensuring the
      data is in the expected format for the next steps in the data pipeline.
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
    columns:
      - name: customer_id
        tests:
          - unique:
              config:
                severity: warn
          - relationships:
              to: ref('stg_signups')
              field: customer_id

  - name: stg_orders
    description: This model represents a staging table for orders data. It serves
      the finance and sales teams by providing a clean and consistent data source
      for downstream reporting and analysis. The model renames and selects the relevant
      columns from the raw orders data, including the order ID, customer ID, order
      date, and order status.
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance", "sales"]
      elementary:
        timestamp_column: "order_date"
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
      - name: status
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["placed", "shipped", "completed", "return_pending", "returned"]
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["placed", "shipped", "completed", "return_pending", "returned"]
              quote_values: true

  - name: stg_payments
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
        tests:
          - unique:
              config:
                severity: warn
      - name: payment_method
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["credit_card", "coupon", "bank_transfer", "gift_card"]

  - name: stg_signups
    description: This model represents the staging table for the signups data in the
      Jaffle Shop online business. It ingests the raw signups data from the `raw_signups_training`
      table, and performs basic transformations to extract the relevant signup details
      such as the signup ID, customer ID, customer email, hashed password, and signup
      date. This data is used to support customer analysis and reporting, as well
      as to enable further downstream data processing and modeling.
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
      elementary:
        timestamp_column: "signup_date"
    columns:
      - name: signup_id
        tests:
          - unique:
              config:
                severity: warn
      - name: customer_email
        tests:
          - unique
          - elementary.column_anomalies:
              sensitivity: 2
              config:
                severity: warn
              column_anomalies:
                - missing_count
