version: 2

models:
  - name: orders
    tests:
      - unique:
          column_name: order_id
      - elementary.column_anomalies:
          column_name: amount
          anomaly_direction: both
          anomaly_sensitivity: 2
          detection_period: 2d
          timestamp_column: order_date

  - name: real_time_orders
    tests:
      - elementary.custom_sql_test:
          name: amount_less_than_max_price
          config:
            severity: error
          query: |
            SELECT
              real_time_orders.order_id,
              real_time_orders.amount,
              raw_products.max_price
            FROM {{ model }} AS real_time_orders
            JOIN {{ source('raw', 'products') }} AS raw_products
              ON real_time_orders.product_id = raw_products.product_id
            WHERE real_time_orders.amount > raw_products.max_price

  - name: stg_orders
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies

  - name: stg_payments
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies
