
version: 2

models:
  - name: orders
    columns:
      - name: order_id
        tests:
          - unique
      - name: amount
        tests:
          - elementary.column_anomalies:
              anomaly_sensitivity: 3
              column_anomalies:
                - average

  - name: real_time_orders
    tests:
      - custom_test_name: amount_validation
        test_description: Validate that amount is less than or equal to max price from raw_products
        test_query: |
          SELECT 
            rto.order_id,
            rto.amount,
            rp.max_price
          FROM {{ ref('real_time_orders') }} rto
          LEFT JOIN {{ ref('raw_products') }} rp ON rto.product_id = rp.product_id
          WHERE rto.amount > rp.max_price

  - name: stg_orders
    tests:
      - elementary.volume_anomalies:
          anomaly_sensitivity: 3
      - elementary.freshness_anomalies:
          timestamp_column: created_at
          anomaly_sensitivity: 3

  - name: stg_payments
    tests:
      - elementary.volume_anomalies:
          anomaly_sensitivity: 3
      - elementary.freshness_anomalies:
          timestamp_column: payment_date
          anomaly_sensitivity: 3
