models:
  - name: cpa_and_roas
    tests:
      - not_null:
          column_name: total_spend
      - not_null:
          column_name: attribution_points
      - not_null:
          column_name: attribution_revenue
      - accepted_values:
          values: ['>=0']
          column_name: total_spend
      - accepted_values:
          values: ['>=0']
          column_name: attribution_revenue
      - accepted_values:
          values: ['>=0']
          column_name: cost_per_acquisition
      - accepted_values:
          values: ['>=0']
          column_name: return_on_advertising_spend
      - custom_generic_test:
          config:
            severity: error
          test_name: date_not_in_future
          test_description: "Check that 'day' column is not in the future"
          test_query: >
            SELECT *
            FROM {{ model }}
            WHERE day > CURRENT_DATE()
      - custom_generic_test:
          config:
            severity: error
          test_name: spend_attribution_relationship
          test_description: "Check relationship integrity between spend and attribution data"
          test_query: >
            SELECT *
            FROM {{ model }}
            WHERE total_spend > 0
              AND (attribution_points <= 0 OR attribution_revenue <= 0)