version: 2

models:
  - name: stg_customers
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
    columns:
      - name: customer_id
        tests:
          - unique:
              config:
                severity: warn
          - relationships:
              to: ref('stg_signups')
              field: customer_id

    description: This model represents the staged customer data from the raw `raw_customers_validation`
      table in the `jaffle_shop` schema. It extracts and renames the key customer
      attributes, including `customer_id`, `first_name`, and `last_name`, to provide
      a clean and consistent data source for downstream analytics. This model serves
      as a foundation for further data processing and analysis related to customer
      information, enabling data consumers to easily access and work with standardized
      customer data.
  - name: stg_orders
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance", "sales"]
      elementary:
        timestamp_column: "order_date"
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
      - name: status
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["placed", "shipped", "completed", "return_pending", "returned"]
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["placed", "shipped", "completed", "return_pending", "returned"]
              quote_values: true

    description: This model serves as the staging layer for order data in the finance
      and sales domains. It takes the raw order data from the `ELEMENTARY_TESTS.jaffle_shop.raw_orders_validation`
      table and renames the columns to more intuitive names, such as `order_id`, `customer_id`,
      `order_date`, and `status`. This transformed data is then made available to
      downstream analytical models, providing a clean and consistent representation
      of the order information.
  - name: stg_payments
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
        tests:
          - unique:
              config:
                severity: warn
      - name: payment_method
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["credit_card", "coupon", "bank_transfer", "gift_card"]

    description: This model, `stg_payments`, represents the staging table for payment
      data in the finance domain. It serves as a centralized and cleaned source of
      payment information for downstream analytics and reporting. The model extracts
      and renames the relevant columns from the raw `raw_payments_validation` table,
      and performs a key transformation by converting the `amount` column from cents
      to dollars to provide a more user-friendly representation of the payment amounts.
  - name: stg_signups
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
      elementary:
        timestamp_column: "signup_date"
    columns:
      - name: signup_id
        tests:
          - unique:
              config:
                severity: warn
      - name: customer_email
        tests:
          - unique
          - elementary.column_anomalies:
              sensitivity: 2
              config:
                severity: warn
              column_anomalies:
                - missing_count
