version: 2

models:
  - name: stg_customers
    description: This model, `stg_customers`, represents the staging table for customer
      data in the Jaffle Shop data warehouse. It serves the purpose of providing a
      clean, structured, and consistent data source for downstream analysis and reporting.
      The model extracts and renames the relevant columns from the `raw_customers_validation`
      table, including `customer_id`, `first_name`, and `last_name`. This staging
      model is a critical step in the data transformation process, ensuring that the
      customer data is ready for further analysis and integration with other data
      sources.
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
    columns:
      - name: customer_id
        tests:
          - unique:
              config:
                severity: warn
          - relationships:
              to: ref('stg_signups')
              field: customer_id

  - name: stg_orders
    description: This model represents the staging table for the orders data from
      the jaffle_shop data source. It serves the finance and sales teams by providing
      a cleansed and standardized version of the raw orders data, including the order
      ID, customer ID, order date, and order status. The key transformations performed
      are renaming the columns to more intuitive names and removing any invalid or
      corrupt data from the raw source.
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance", "sales"]
      elementary:
        timestamp_column: "order_date"
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
      - name: status
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["placed", "shipped", "completed", "return_pending", "returned"]
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["placed", "shipped", "completed", "return_pending", "returned"]
              quote_values: true

  - name: stg_payments
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
        tests:
          - unique:
              config:
                severity: warn
      - name: payment_method
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["credit_card", "coupon", "bank_transfer", "gift_card"]

  - name: stg_signups
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
      elementary:
        timestamp_column: "signup_date"
    columns:
      - name: signup_id
        tests:
          - unique:
              config:
                severity: warn
      - name: customer_email
        tests:
          - unique
          - elementary.column_anomalies:
              sensitivity: 2
              config:
                severity: warn
              column_anomalies:
                - missing_count
