version: 2

models:
  - name: orders
    tests:
      - unique:
          column_name: order_id
      - elementary.column_anomalies:
          column_name: amount
          anomaly_direction: both
          detection_period: 7
          sensitivity: 3

  - name: real_time_orders
    tests:
      - elementary.custom_sql:
          name: amount_less_than_max_price
          query: |
            SELECT
              order_id,
              amount,
              max_price
            FROM {{ model }} AS real_time_orders
            LEFT JOIN raw_products ON real_time_orders.product_id = raw_products.product_id
            WHERE amount > max_price

  - name: stg_orders
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies

  - name: stg_payments
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies
