version: 2

models:
  - name: stg_customers
    description: This model represents the staging table for customer data. It fetches
      the raw customer data from the `raw_customers_validation` table in the `jaffle_shop`
      schema and renames the columns to a more business-friendly format. The purpose
      of this model is to provide a clean, standardized dataset for downstream analysis
      and transformation, ensuring data quality and consistency for the customer-related
      metrics and reports.
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
    columns:
      - name: customer_id
        tests:
          - unique:
              config:
                severity: warn
          - relationships:
              to: ref('stg_signups')
              field: customer_id

  - name: stg_orders
    description: 'This model represents the staging table for orders in the jaffle_shop
      database. It serves as the intermediate layer between the raw data and the downstream
      models, providing a clean and standardized view of the order data. The model
      performs the following key transformations: it renames the columns from the
      raw data to more descriptive names (e.g., `id` to `order_id`, `user_id` to `customer_id`)
      and selects the relevant fields (order ID, customer ID, order date, and status)
      for downstream consumption.'
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance", "sales"]
      elementary:
        timestamp_column: "order_date"
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
      - name: status
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["placed", "shipped", "completed", "return_pending", "returned"]
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["placed", "shipped", "completed", "return_pending", "returned"]
              quote_values: true

  - name: stg_payments
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
        tests:
          - unique:
              config:
                severity: warn
      - name: payment_method
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["credit_card", "coupon", "bank_transfer", "gift_card"]

  - name: stg_signups
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
      elementary:
        timestamp_column: "signup_date"
    columns:
      - name: signup_id
        tests:
          - unique:
              config:
                severity: warn
      - name: customer_email
        tests:
          - unique
          - elementary.column_anomalies:
              sensitivity: 2
              config:
                severity: warn
              column_anomalies:
                - missing_count
