version: 2

models:
  - name: orders
    tests:
      - unique:
          column_name: order_id  # Assuming order_id is the primary key
      - elementary.column_anomalies:
          column_name: amount
          anomaly_sensitivity: 3
          anomaly_direction: both
          timestamp_column: order_date  # Assuming there's an order_date column

  - name: real_time_orders
    tests:
      - elementary.expression_is_true:
          expression: 'amount <= (select max(price) from {{ source(''raw'', ''products'') }})'
          description: 'Validate that amount is not greater than the maximum price in raw_products'

  - name: stg_orders
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies

  - name: stg_payments
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies
