models:
  - name: ads_spend
    columns:
      - name: day
        tests:
          - not_null
      - name: utm_source
        tests:
          - not_null
      - name: utm_medium
        tests:
          - not_null
      - name: utm_campaign
        tests:
          - not_null
      - name: spend
        tests:
          - not_null
          - positive_value
    tests:
      - unique:
          column_name:
            - day
            - utm_source
            - utm_medium
            - utm_campaign
      - dbt_utils.accepted_range:
          column_name: day
          min_value: '2020-01-01'  # Adjust this date as needed
          max_value: "{{ dbt_utils.current_timestamp() }}"
          inclusive: true
