version: 2

models:
  - name: stg_orders
    description: Staging layer for orders data
    config:
      tags: ["staging", "daily"]
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    description: Staging layer for payments data
    config:
      tags: ["staging", "daily"]
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
