models:
  - name: ads_spend
    columns:
      - name: day
        tests:
          - not_null
      - name: utm_source
        tests:
          - not_null
      - name: utm_medium
        tests:
          - not_null
      - name: utm_campain
        tests:
          - not_null
      - name: spend
        tests:
          - not_null
          - positive_values
    tests:
      - unique:
          column_name:
            - day
            - utm_source
            - utm_medium
            - utm_campain
      - elementary.freshness:
          column_name: day
          maximal_days_allowed: 7

# Custom generic test for positive values
tests:
  - name: positive_values
    description: Ensures that the specified column only contains positive values
    tests:
      - accepted_values:
          values: ['>0']
