version: 2

models:
  - name: stg_customers
    description: This model represents a staging table for customer data, including
      customer ID, first name, and last name. It serves as the foundation for further
      analysis and reporting on customer information. The model performs a simple
      renaming of the source columns from the `raw_customers_validation` table in
      the `jaffle_shop` schema.
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
    columns:
      - name: customer_id
        tests:
          - unique:
              config:
                severity: warn
          - relationships:
              to: ref('stg_signups')
              field: customer_id

  - name: stg_orders
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance", "sales"]
      elementary:
        timestamp_column: "order_date"
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
      - name: status
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["placed", "shipped", "completed", "return_pending", "returned"]
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["placed", "shipped", "completed", "return_pending", "returned"]
              quote_values: true

  - name: stg_payments
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
        tests:
          - unique:
              config:
                severity: warn
      - name: payment_method
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["credit_card", "coupon", "bank_transfer", "gift_card"]

  - name: stg_signups
    description: This model represents the staging table for signup data, which contains
      personally identifiable information (PII) about users who have signed up for
      the application. It is used to capture the raw signup data, including the user's
      unique identifier, email address, hashed password, and the date they signed
      up. This model serves as a foundation for downstream data analysis and reporting
      on user signups and registration activity.
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
      elementary:
        timestamp_column: "signup_date"
    columns:
      - name: signup_id
        tests:
          - unique:
              config:
                severity: warn
      - name: customer_email
        tests:
          - unique
          - elementary.column_anomalies:
              sensitivity: 2
              config:
                severity: warn
              column_anomalies:
                - missing_count
