version: 2

models:
  - name: stg_customers
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
    columns:
      - name: customer_id
        tests:
          - unique:
              config:
                severity: warn
          - relationships:
              to: ref('stg_signups')
              field: customer_id

    data_tests:
      - elementary.all_columns_anomalies:
          column_anomalies: # Optional, A list of column monitors for anomaly detection.
            - null_count
            - null_percent
            - min_length
            - max_length
            - average_length
            - missing_count
            - missing_percent
            - min
            - max
            - average
            - zero_count
            - zero_percent
            - standard_deviation
            - variance
            - sum
          exclude_prefix: id_ # Optional, Columns with this prefix will be excluded from the test.
          exclude_regexp: .*SDC$ # Optional, Columns matching this regular expression will be excluded from the test.
          time_bucket: # Optional, The period for time bucketing.
            period: day
            count: 1
          timestamp_column: created_at # Optional, The timestamp column to use in order to split the data into time buckets.
          anomaly_sensitivity: 3 # Optional, The sensitivity level for anomaly detection.
          training_period: # Optional, The period for model training.
            period: day # Optional
            count: 14 # Optional
          detection_period: # Optional, The period for anomaly detection.
            period: day # Optional
            count: 2 # Optional
          anomaly_direction: both # Optional, The direction of anomalies to detect.
          config:
            severity: warn
  - name: stg_orders
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance", "sales"]
      elementary:
        timestamp_column: "order_date"
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
      - name: status
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["placed", "shipped", "completed", "return_pending", "returned"]
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["placed", "shipped", "completed", "return_pending", "returned"]
              quote_values: true

    data_tests:
      - elementary.all_columns_anomalies:
          column_anomalies: # Optional, A list of column monitors for anomaly detection.
            - null_count
            - null_percent
            - min_length
            - max_length
            - average_length
            - missing_count
            - missing_percent
            - min
            - max
            - average
            - zero_count
            - zero_percent
            - standard_deviation
            - variance
            - sum
          exclude_prefix: id_ # Optional, Columns with this prefix will be excluded from the test.
          exclude_regexp: .*SDC$ # Optional, Columns matching this regular expression will be excluded from the test.
          time_bucket: # Optional, The period for time bucketing.
            period: day
            count: 1
          timestamp_column: created_at # Optional, The timestamp column to use in order to split the data into time buckets.
          anomaly_sensitivity: 3 # Optional, The sensitivity level for anomaly detection.
          training_period: # Optional, The period for model training.
            period: day # Optional
            count: 14 # Optional
          detection_period: # Optional, The period for anomaly detection.
            period: day # Optional
            count: 2 # Optional
          anomaly_direction: both # Optional, The direction of anomalies to detect.
          config:
            severity: warn
  - name: stg_payments
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
        tests:
          - unique:
              config:
                severity: warn
      - name: payment_method
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["credit_card", "coupon", "bank_transfer", "gift_card"]

    data_tests:
      - elementary.all_columns_anomalies:
          column_anomalies: # Optional, A list of column monitors for anomaly detection.
            - null_count
            - null_percent
            - min_length
            - max_length
            - average_length
            - missing_count
            - missing_percent
            - min
            - max
            - average
            - zero_count
            - zero_percent
            - standard_deviation
            - variance
            - sum
          exclude_prefix: id_ # Optional, Columns with this prefix will be excluded from the test.
          exclude_regexp: .*SDC$ # Optional, Columns matching this regular expression will be excluded from the test.
          time_bucket: # Optional, The period for time bucketing.
            period: day
            count: 1
          timestamp_column: created_at # Optional, The timestamp column to use in order to split the data into time buckets.
          anomaly_sensitivity: 3 # Optional, The sensitivity level for anomaly detection.
          training_period: # Optional, The period for model training.
            period: day # Optional
            count: 14 # Optional
          detection_period: # Optional, The period for anomaly detection.
            period: day # Optional
            count: 2 # Optional
          anomaly_direction: both # Optional, The direction of anomalies to detect.
          config:
            severity: warn
  - name: stg_signups
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "pii"]
      elementary:
        timestamp_column: "signup_date"
    columns:
      - name: signup_id
        tests:
          - unique:
              config:
                severity: warn
      - name: customer_email
        tests:
          - unique
          - elementary.column_anomalies:
              sensitivity: 2
              config:
                severity: warn
              column_anomalies:
                - missing_count
    data_tests:
      - elementary.all_columns_anomalies:
          column_anomalies: # Optional, A list of column monitors for anomaly detection.
            - null_count
            - null_percent
            - min_length
            - max_length
            - average_length
            - missing_count
            - missing_percent
            - min
            - max
            - average
            - zero_count
            - zero_percent
            - standard_deviation
            - variance
            - sum
          exclude_prefix: id_ # Optional, Columns with this prefix will be excluded from the test.
          exclude_regexp: .*SDC$ # Optional, Columns matching this regular expression will be excluded from the test.
          time_bucket: # Optional, The period for time bucketing.
            period: day
            count: 1
          timestamp_column: created_at # Optional, The timestamp column to use in order to split the data into time buckets.
          anomaly_sensitivity: 3 # Optional, The sensitivity level for anomaly detection.
          training_period: # Optional, The period for model training.
            period: day # Optional
            count: 14 # Optional
          detection_period: # Optional, The period for anomaly detection.
            period: day # Optional
            count: 2 # Optional
          anomaly_direction: both # Optional, The direction of anomalies to detect.
          config:
            severity: warn
