version: 2

models:
  - name: orders
    tests:
      - unique:
          column_name: order_id
    columns:
      - name: amount
        tests:
          - elementary.column_anomalies:
              anomaly_direction: both
              sensitivity: 2
              column_anomalies:
                - average

  - name: real_time_orders
    tests:
      - elementary.custom_sql:
          description: Validate that amount is less than or equal to max price from raw_products
          query: |
            SELECT
              rto.order_id,
              rto.amount,
              rp.max_price
            FROM {{ model }} rto
            JOIN {{ ref('raw_products') }} rp ON rto.product_id = rp.product_id
            WHERE rto.amount > rp.max_price

  - name: stg_orders
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies

  - name: stg_payments
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies
