version: 2

sources:
  - name: sessions
    tables:
      - name: stg_app_sessions
        owner: DE-engineering-team
      - name: stg_website_sessions
        owner: DE-engineering-team

  - name: ads
    tables:
      - name: stg_google_ads
        owner: DE-engineering-team
      - name: stg_instagram_ads
        owner: DE-engineering-team
      - name: stg_facebook_ads
        owner: DE-engineering-team
