models:
  - name: stg_orders
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies:
          timestamp_column: created_at  # Assuming there's a created_at column

  - name: stg_payments
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies:
          timestamp_column: payment_date  # Assuming there's a payment_date column
