version: 2

models:
  - name: orders
    tests:
      - unique:
          column_name: order_id
      - elementary.column_anomalies:
          column_name: amount

  - name: real_time_orders
    tests:
      - elementary.custom_sql:
          sql: |
            select * from {{ model }} where amount > (select max(price) from raw_products)

  - name: stg_orders
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies

  - name: stg_payments
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies
