version: 2

sources:
  - name: ads
    schema: jaffle_shop
    tables:
      - name: stg_google_ads
        columns:
          - name: ad_id
            data_tests:
              - unique:
                  meta:
                    owner:
                      - Idan
                    description: The column should contain only unique values
      - name: stg_facebook_ads
        columns:
          - name: ad_id
            data_tests:
              - unique:
                  meta:
                    owner:
                      - Idan
                    description: The column should contain only unique values
      - name: stg_instagram_ads

        columns:
          - name: ad_id
            data_tests:
              - unique:
                  meta:
                    owner:
                      - Idan
                    description: The column should contain only unique values
  - name: sessions
    schema: jaffle_shop
    tables:
      - name: stg_website_sessions
        columns:
          - name: ad_id
            data_tests:
              - unique:
                  meta:
                    owner:
                      - Idan
                    description: The column should contain only unique values
          - name: customer_id
            data_tests:
              - unique:
                  meta:
                    owner:
                      - Idan
                    description: The column should contain only unique values
          - name: session_id
            data_tests:
              - unique:
                  meta:
                    owner:
                      - Idan
                    description: The column should contain only unique values
      - name: stg_app_sessions
        columns:
          - name: ad_id
            data_tests:
              - unique:
                  meta:
                    owner:
                      - Idan
                    description: The column should contain only unique values
          - name: customer_id
            data_tests:
              - unique:
                  meta:
                    owner:
                      - Idan
                    description: The column should contain only unique values
          - name: session_id
            data_tests:
              - unique:
                  meta:
                    owner:
                      - Idan
                    description: The column should contain only unique values
