version: 2

sources:
  - name: ads
    schema: "{{ target.schema }}"
    tables:
      - name: stg_google_ads
        columns:
          - name: ad_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - stability
                    severity: error
                  meta:
                    owner:
                      - Or
      - name: stg_facebook_ads
        columns:
          - name: ad_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - stability
                    severity: error
                  meta:
                    owner:
                      - Or
      - name: stg_instagram_ads

        columns:
          - name: ad_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - stability
                    severity: error
                  meta:
                    owner:
                      - Or
  - name: sessions
    schema: "{{ target.schema }}"
    tables:
      - name: stg_website_sessions
        columns:
          - name: ad_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - stability
                    severity: error
                  meta:
                    owner:
                      - Or
          - name: customer_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - stability
                    severity: error
                  meta:
                    owner:
                      - Or
          - name: session_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - stability
                    severity: error
                  meta:
                    owner:
                      - Or
      - name: stg_app_sessions
        columns:
          - name: ad_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - stability
                    severity: error
                  meta:
                    owner:
                      - Or
          - name: customer_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - stability
                    severity: error
                  meta:
                    owner:
                      - Or
          - name: session_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - stability
                    severity: error
                  meta:
                    owner:
                      - Or
