version: 2

sources:
  - name: ads
    schema: jaffle_shop
    tables:
      - name: stg_google_ads
        columns:
          - name: ad_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - marketing
                  meta:
                    owner:
                      - Ella
      - name: stg_facebook_ads
        columns:
          - name: ad_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - marketing
                  meta:
                    owner:
                      - Ella
      - name: stg_instagram_ads

        columns:
          - name: ad_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - marketing
                  meta:
                    owner:
                      - Ella
  - name: sessions
    schema: jaffle_shop
    tables:
      - name: stg_website_sessions
        columns:
          - name: ad_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - marketing
                  meta:
                    owner:
                      - Ella
          - name: customer_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - marketing
                  meta:
                    owner:
                      - Ella
          - name: session_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - marketing
                  meta:
                    owner:
                      - Ella
      - name: stg_app_sessions
        columns:
          - name: ad_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - marketing
                  meta:
                    owner:
                      - Ella
          - name: customer_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - marketing
                  meta:
                    owner:
                      - Ella
          - name: session_id
            data_tests:
              - unique:
                  description: The column should contain only unique values
                  config:
                    tags:
                      - marketing
                  meta:
                    owner:
                      - Ella
