version: 2

sources:
  - name: ads
    schema: jaffle_shop
    tables:
      - name: stg_google_ads
        data_tests:
          - dbt_expectations.expect_column_pair_values_to_be_equal:
              column_A: col_numeric_a
              column_B: col_numeric_a
              row_condition: id is not null # Optional
              config:
                severity: error
      - name: stg_facebook_ads
      - name: stg_instagram_ads

  - name: sessions
    schema: jaffle_shop
    tables:
      - name: stg_website_sessions
      - name: stg_app_sessions
