version: 2

models:
  - name: cpa_and_roas
    description: 'Model for calculating Cost Per Acquisition (CPA) and Return on Ad Spend (ROAS)'
    columns:
      - name: day
        description: 'The date of the ad spend and revenue data'
      - name: utm_source
        description: 'The source of the traffic (e.g., Google, Facebook)'
      - name: total_spend
        description: 'Total amount spent on ads for this day and source'
      - name: attribution_points
        description: 'Number of conversions attributed to this day and source'
      - name: attribution_revenue
        description: 'Revenue attributed to this day and source'
      - name: cost_per_acquisition
        description: 'Calculated CPA (total_spend / attribution_points)'
      - name: return_on_advertising_spend
        description: 'Calculated ROAS (attribution_revenue / total_spend)'
    meta:
      owner: 'Or'
      subscribers: '@marketing_team'
