models:
  - name: cpa_and_roas
    meta:
      subscribers: "@marketing_team"
    columns:
      - name: day
        tests:
          - not_null
      - name: utm_source
        tests:
          - not_null
      - name: total_spend
        tests:
          - not_null
      - name: attribution_points
        tests:
          - not_null
      - name: attribution_revenue
        tests:
          - not_null
      - name: cost_per_acquisition
      - name: return_on_advertising_spend