models:
  - name: cpa_and_roas
    meta:
      subscribers: [@marketing_team]
    columns:
      - name: RETURN_ON_ADVERTISING_SPEND
        description: "The return on advertising spend (ROAS) calculation"
