version: 2

models:
  - name: cpa_and_roas
    description: This table contains the cost per acquisition and return on ad spend, by source, and per day
    columns:
      - name: date
        description: The date of the record
        tests:
          - not_null
          - unique
      - name: source
        description: The marketing source (e.g., Google Ads, Facebook Ads)
        tests:
          - not_null
      - name: spend
        description: The amount spent on ads for this source and date
        tests:
          - not_null
      - name: revenue
        description: The revenue attributed to ads from this source and date
        tests:
          - not_null
      - name: cpa
        description: Cost per acquisition (spend / number of acquisitions)
        tests:
          - not_null
      - name: roas
        description: Return on ad spend (revenue / spend)
        tests:
          - not_null
    meta:
      owner: Noa
      subscribers:
        - "@marketing_team"