version: 2

models:
  - name: cpa_and_roas
    description: This table contains the cost per acquisition and return on ad spend, by source, and per month
    columns:
      - name: date_month
        tests:
          - not_null
      - name: utm_source
        tests:
          - not_null
      - name: total_spend
        tests:
          - not_null
      - name: attribution_points
        tests:
          - not_null
      - name: attribution_revenue
        tests:
          - not_null
    tests:
      - schema_changes_from_baseline

  - name: attribution_touches
    columns:
      - name: linear_revenue
        tests:
          - not_null
    tests:
      - schema_changes_from_baseline