version: 2

models:
  - name: cpa_and_roas
    config:
      owner: de-engineering-team
  - name: orders
    config:
      owner: de-engineering-team
  - name: attribution_touches
    config:
      owner: de-engineering-team
  - name: sessions
    config:
      owner: de-engineering-team
  - name: ads_spend
    config:
      owner: de-engineering-team
